### ISSUE TITLE
PHP 7 Cannot use 'Float' as class name

### ISSUE THREAD

**Issue by ickbinhier** [h4kuna/data-type#1]
i have a problem in PHP 7

Cannot use 'Float' as class name as it is reserved in ..../vendor/h4kuna/data-type/Float.php line 12

**Comment by ickbinhier** [comment]
https://github.com/h4kuna/data-type/pull/2

**Comment by h4kuna** [comment]
I prepare new version, will be renamed. Bud objects are [static](/h4kuna/data-type/tree/phpunit-tests), and I am not sure if is right.

**Comment by h4kuna** [comment]
Name of class must be compatible as prepared version. For forward compatibility.

**Comment by ickbinhier** [comment]
i have close the pull request.

the branch phpunit-tests works for me. this version is stable, or will change a lot?

**Comment by h4kuna** [comment]
Now is working https://travis-ci.org/h4kuna/data-type/builds/93307677 but classes are static and i am thinking about back compatibility or if is need. You can test it. And tell me if work with this new classes are good.

**Comment by h4kuna** [comment]
This branche will be stable. If i have answer on previous question :)

**Comment by h4kuna** [comment]
I think static classes are good because PHP 7 has scalar type hint, that you don't need object type.

**Comment by ickbinhier** [comment]
this works for me perfectly and is shorter.

I do not think you have to pay at the point too much on the return value compatibility. If you have a version 2 do may also change the interfaces.

When can we expect a stable release?

new
$request_value = Floats::fromString($request_value);

old
$float = new Float($request_value);
$request_value = $float->getValue();

**Comment by h4kuna** [comment]
Today :) 5 minutes

**Comment by ickbinhier** [comment]
perfect.
