### ISSUE TITLE
Float::fromString with german tausender Punkt

### ISSUE THREAD

**Issue by ickbinhier** [h4kuna/data-type#4]
Float::fromString('3.620,00');

h4kuna\DataType\InvalidArgumentsException:
This value is not float: 3.620,00

  at vendor/h4kuna/data-type/src/Basic/Floats.php:45
  at h4kuna\DataType\Basic\Floats::fromString('3.620,00')
     (src/Sz/Bundle/ModulIdafBundle/Controller/TeilnehmerController.php:289)
  at Sz\Bundle\ModulIdafBundle\Controller\TeilnehmerController->druckenAction(object(Person), object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:29)

**Comment by h4kuna** [comment]
Thank you for report, i fix it and release version 2.1.5. 
I add two parameters where define decimal point and thousands separator.
```php
echo Floats::fromString('3.620,00', ',', '.');
```
I recommended you write own class where is 
```php
namespace MyNamespace;

use h4kuna\DataType\Basic;

class Floats
{

	public static function fromString($value)
	{
		return Basic\Floats::fromString($value, ',', '.');
	}
}
```

And use without two last parameters
```php
echo Floats::fromString('3.620,00');
```
